name: blurbox
description: "A Flutter package that applies a blur effect to its child widget."
version: 0.0.4
homepage: https://github.com/OmidHaqi/blurbox

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
