# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2  # Installs Flutter
        with:
          channel: 'stable'  # Or 'beta', 'master'

      - uses: actions/setup-java@v3  # Optional: If your project uses Java
        with:
          distribution: 'temurin'
          java-version: '17'  # Or your preferred version

      - name: Create environment file
        run: echo "PATH=$PATH:$HOME/.flutter/bin" >> $GITHUB_ENV/flutter_path

      - name: Load environment file
        run: source $GITHUB_ENV/flutter_path

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze
